version: "2"
services:
  app:
    build: ./app
    links:
     - mysql
    ports:
     - "5000:5000"
    env_file: database.conf
  mysql:
    image: mysql:5.7
    ports:
     - "32000:3306"
    environment: 
     MYSQL_ROOT_PASSWORD: Teju@2019
    volumes:
     - ./db:/docker-entrypoint-initdb.d/:ro
